# -*- coding: utf-8 -*-
"""BB84_QKD_Simulator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eZ16Qi0JXeluNj-ZB8E5i1dnjoxdT-Rc
"""

import numpy as np
n = int(input("Enter number of bits: "))
Sender_bits = [int(x) for x in np.random.randint(2, size=n)]
Sender_bases = [str(x) for x in np.random.choice(['R', 'D'], size=n)]
Receiver_bases = [str(x) for x in np.random.choice(['R', 'D'], size=n)]
Receiver_bits = []
for i in range(n):
    if Sender_bases[i] == Receiver_bases[i]:
        Receiver_bits.append(int(Sender_bits[i]))
    else:
        Receiver_bits.append(np.random.randint(2))
match_count = 0
Secret_key = []
for i in range(n):
    if Sender_bases[i] == Receiver_bases[i]:
       Secret_key.append(int(Receiver_bits[i]))
       match_count += 1
print("Sender bits :", Sender_bits)
print("Sender bases:", Sender_bases)
print("Receiver bases  :", Receiver_bases)
print("Receiver bits   :", Receiver_bits)
print("Matching bases count:", match_count)
print("Secret key:", Secret_key)

